name: Test backend for now

on:
  push:
    branches:
      - main
      - mikhail

jobs:
  flake8_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.0.0 flake8-isort==6.0.0
    - name: Run static tests with flake8
      run: |
        python -m flake8 backend/



  # automatic_test:
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:13
  #       env:
  #         POSTGRES_USER: trial_user
  #         POSTGRES_PASSWORD: trial_password
  #         POSTGRES_DB: trial
  #       ports:
  #         - 5432:5432
  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-python@v4
  #     with:
  #       python-version: 3.9
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r ./backend/requirements.txt
  #   - name: Run static tests with flake8
  #     run: |
  #       python -m flake8 backend/
  #   - name: Run automatic tests
  #     env:
  #       POSTGRES_USER: trial_user
  #       POSTGRES_PASSWORD: trial_password
  #       POSTGRES_DB: trial
  #       DB_HOST: 127.0.0.1
  #       DB_PORT: 5432
  #     run: |
  #       pytest tests/
